int cable_open(void);
void cable_close(void);
int cable_load(unsigned char memory, unsigned char bank, int start, int end, char* data, int size);
int cable_save(unsigned char memory, unsigned char bank, int start, int end, char* data, int size);
int cable_peek(unsigned char memory, unsigned char bank, int address, unsigned char* value);
int cable_poke(unsigned char memory, unsigned char bank, int address, unsigned char value);
int cable_jump(unsigned char memory, unsigned char bank, int address);
int cable_run(void);
int cable_reset(void);
__inline__ unsigned char cable_read(void);
__inline__ void cable_write(unsigned char byte);
__inline__ int cable_write_with_timeout(unsigned char byte);
__inline__ void _cable_send_signal_input(void);
__inline__ void _cable_send_signal_output(void);
__inline__ int _cable_receive_signal(struct timeval* timeout); 
